services:
  wireguard:
    image: linuxserver/wireguard:v1.0.20210914-ls7
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
    ports:
      - "5000:5000"
      - "51820:51820/udp"
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    # use the network of the 'wireguard' service. this enables to show active clients in the status page
    network_mode: service:wireguard
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SENDGRID_API_KEY
      # ddns or public ip + port forwarding endpoint
      - WGUI_ENDPOINT_ADDRESS=ddns:51825
      - WGUI_LOG_LEVEL=INFO
      - EMAIL_FROM_ADDRESS=lecongquynhh@gmail.com
      - EMAIL_FROM_NAME=WireGuard HomeServer
      - SMTP_HOSTNAME=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_AUTH_TYPE=LOGIN
      - SMTP_ENCRYPTION=TLS
      - SMTP_USERNAME=username@gmail.com
      - SMTP_PASSWORD=apppassword
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./config:/etc/wireguard
    restart: unless-stopped
